type Producer {
    _id: String
    name: String
    country: String
    region: String
}

type Product {
    _id: String!
    vintage: String
    name: String!
    producerId: String!
    producer: Producer
}

input CreateProductParams {
    name: String!
    producerId: String!
    vintage: String
}

type Query {
    getProducts: [Product]
    getProductById(productId: String): Product
    getProductsByProducer(producerId: String!): [Product]
}

type Mutation {
    addProduct(params: [CreateProductParams]!): [Product]
    updateProduct(productId: String!, name: String, vintage: String, producerId: String): Product
    deleteProducts(productIds: [String]!): Boolean
    syncProducts: Boolean
}